// <>
//   <LogoutPage/>
//   <RegisterPage 
//     inputPasswordHandler={onPasswordChangeHandler}
//     inputEmailHandler={onEmailChangeHandler}
//     inputNamelHandler={onNameChangeHandler}
//     state={state}
//   />
// </>